// Library: VLANs, host pools, address pools, VRFs - the configuration everything else draws on.
import { get, post, errorPanel } from '../api.js';
import { h, mount, card, table, tabs, button, input, select, field, modal, toast, chip } from '../dom.js';

const ZONES = ['', 'Internal', 'DataCentre', 'DMZ', 'OOB', 'Perimeter'];

export async function render(root, active = 'vlans') {
  const body = h('div');
  const bar = h('div');
  const show = async (id) => {
    active = id;
    mount(bar, tabs([
      { id: 'vlans', label: 'VLAN library' }, { id: 'roles', label: 'Host pools' }, { id: 'pools', label: 'Address pools' }, { id: 'vrfs', label: 'VRFs' },
    ], active, show));
    mount(body, h('p', { class: 'muted' }, 'Loading…'));
    try { mount(body, await VIEWS[id](() => show(id))); } catch (err) { mount(body, errorPanel(err)); }
  };
  mount(root, h('h1', {}, 'Library'), h('div', { class: 'card' }, bar, body));
  show(active);
}

const VIEWS = {
  async vlans(refresh) {
    const vlans = await get('/vlans');
    const q = input({ placeholder: 'Search key, name, ID or alias…', class: 'wide' });
    const cls = select([{ value: '', label: 'All classes' }, ...[...new Set(vlans.map((v) => v.class).filter(Boolean))].sort()], '');
    const hideRule = h('input', { type: 'checkbox', checked: true });
    const box = h('div');
    const draw = () => {
      const s = q.value.trim().toLowerCase();
      const rows = vlans.filter((v) => (!cls.value || v.class === cls.value)
        && (!hideRule.checked || !/-N\d{3}[A-Z]?$/.test(v.vlanKey))
        && (!s || [v.vlanKey, v.vlanName, v.vlanId, ...(v.aliases || [])].join(' ').toLowerCase().includes(s)));
      mount(box, h('p', { class: 'muted small' }, `${rows.length} of ${vlans.length}`), table([
        { label: 'Key', value: (v) => h('code', {}, v.vlanKey) },
        { label: 'ID', value: (v) => v.vlanId ?? '—', class: 'num' },
        { label: 'Name', value: (v) => v.vlanName },
        { label: 'Aliases', value: (v) => (v.aliases || []).join(', ') },
        { label: 'Class', value: (v) => v.class || '' },
        { label: 'Zone', value: (v) => v.securityZone || h('span', { class: 'muted' }, 'none') },
        { label: 'Status', value: (v) => chip(v.status) },
        { label: 'Description', value: (v) => v.description || '' },
      ], rows.slice(0, 500)));
    };
    [q].forEach((el) => el.addEventListener('input', draw));
    [cls, hideRule].forEach((el) => el.addEventListener('change', draw));
    draw();
    return h('div', {},
      h('div', { class: 'row' }, q, cls, h('label', { class: 'check' }, hideRule, ' hide VLANs generated by bulk rules'), h('span', { class: 'spacer' }), button('Add VLAN', () => addVlan(refresh), 'primary')),
      box);
  },

  async roles() {
    const roles = await get('/host-roles');
    return h('div', {},
      h('p', { class: 'muted' }, 'A host pool is a set of standard positions used at every site: e.g. WDC01 is always .61 on the VLANs the pool lives on. Positions are index.octet (1.10 = second /24 of a supernet, octet 10).'),
      table([
        { label: 'Role', value: (r) => h('strong', {}, r.roleCode) },
        { label: 'Name', value: (r) => r.name || '' },
        { label: 'Lives on VLANs', value: (r) => r.vlanKeys.map((k) => h('code', { class: 'pill' }, k)) },
        { label: 'Members', value: (r) => h('div', { class: 'chips' }, r.members.map((m) => h('span', { class: `member member-${m.kind}` }, m.name, ' ',
          h('span', { class: 'muted' }, m.kind === 'fixed' ? `.${String(m.hostPosition).replace(/^0\./, '')}` : `.${m.rangeStart}–.${m.rangeEnd} ${m.kind}`)))) },
        { label: 'Mode', value: (r) => r.offsetMode },
      ], roles));
  },

  async pools() {
    const pools = await get('/pools');
    return table([
      { label: 'Pool', value: (p) => h('strong', {}, p.poolKey) },
      { label: 'Parent', value: (p) => p.parentPool || '—' },
      { label: 'VRF', value: (p) => p.vrf },
      { label: 'Hands out', value: (p) => (p.allocationPrefixLength ? `/${p.allocationPrefixLength}` : '—') },
      { label: 'Prefixes', value: (p) => p.prefixes.map((x) => h('code', { class: 'pill' }, x)) },
      { label: 'Excluded', value: (p) => p.exclusions.map((x) => h('code', { class: 'pill' }, x)) },
      { label: 'Blocks allocated', value: (p) => p.blocksAllocated, class: 'num' },
      { label: 'Uniqueness', value: (p) => p.uniqueness },
    ], pools);
  },

  async vrfs() {
    return table([
      { label: 'VRF', value: (v) => h('strong', {}, v.vrfKey) },
      { label: 'Description', value: (v) => v.description || '' },
    ], await get('/vrfs'));
  },
};

async function addVlan(refresh) {
  const k = input({ class: 'mono', placeholder: 'e.g. DCS-CCTV' });
  const id = input({ type: 'number', min: 2, max: 4094 });
  const name = input({ class: 'mono', placeholder: 'e.g. v2040-CCTV' });
  const aliases = input({ class: 'mono', placeholder: 'comma separated, optional' });
  const cls = input({ class: 'mono', placeholder: 'CORP, DCS, CSMS…' });
  const zone = select(ZONES, '');
  const desc = input({ class: 'wide' });
  const status = h('div');
  const ok = await modal({
    title: 'Add VLAN',
    body: h('div', {}, h('div', { class: 'form-grid' }, field('Key', k, 'UPPER-KEBAB, unique'), field('VLAN ID', id), field('Name', name, 'Unique'), field('Aliases', aliases), field('Class', cls), field('Security zone', zone), field('Description', desc)), status),
    actions: [{ label: 'Cancel', value: false }, {
      label: 'Add', kind: 'primary', value: true,
      validate: async () => {
        try {
          await post('/vlans', {
            vlanKey: k.value.trim().toUpperCase(), vlanId: id.value ? Number(id.value) : null, vlanName: name.value.trim(),
            aliases: aliases.value.split(',').map((a) => a.trim()).filter(Boolean), class: cls.value.trim() || null,
            securityZone: zone.value || null, description: desc.value || null,
          });
          return true;
        } catch (err) { mount(status, errorPanel(err)); return false; }
      },
    }],
  });
  if (ok) { toast('VLAN added', 'success'); refresh(); }
}
