// Library: VLANs, host pools, address pools, VRFs - full add / change / delete (MACD).
// The server refuses deletes while anything uses an item, and says what; the UI shows that list.
import { get, post, patch, api, errorPanel } from '../api.js';
import { h, mount, table, tabs, button, input, select, field, modal, confirmBox, toast, chip, datalist } from '../dom.js';
import { can } from '../session.js';

const ZONES = ['', 'Internal', 'DataCentre', 'DMZ', 'OOB', 'Perimeter'];
const del = (path, query) => api('DELETE', path, { query });
const put = (path, body) => api('PUT', path, { body });

export async function render(root, active = 'vlans') {
  const body = h('div');
  const bar = h('div');
  const show = async (id) => {
    active = id;
    mount(bar, tabs([
      { id: 'vlans', label: 'VLAN library' }, { id: 'roles', label: 'Host pools' }, { id: 'pools', label: 'Address pools' }, { id: 'vrfs', label: 'VRFs' },
    ], active, show));
    mount(body, h('p', { class: 'muted' }, 'Loading…'));
    try { mount(body, await VIEWS[id](() => show(id))); } catch (err) { mount(body, errorPanel(err)); }
  };
  mount(root, h('h1', {}, 'Library'),
    h('p', { class: 'page-sub' }, 'The configuration every template and site draws on. Changes are audited, and never move addresses already held at sites.'),
    h('div', { class: 'card' }, bar, body));
  show(active);
}

/** Run a save; show the server's answer inside the dialog if it refuses. */
function saver(out, fn) {
  return async () => {
    try { await fn(); return true; } catch (err) { mount(out, errorPanel(err)); return false; }
  };
}

function rowActions(...buttons) {
  return h('div', { class: 'actions nowrap' }, buttons.filter(Boolean));
}

function list(raw) {
  return raw.split(/[\s,]+/).map((s) => s.trim()).filter(Boolean);
}

// =========================================================================== VLANs

const VIEWS = {
  async vlans(refresh) {
    const vlans = await get('/vlans');
    const q = input({ placeholder: 'Search key, name, ID or alias…', class: 'wide' });
    const cls = select([{ value: '', label: 'All classes' }, ...[...new Set(vlans.map((v) => v.class).filter(Boolean))].sort()], '');
    const hideRule = h('input', { type: 'checkbox', checked: true });
    const box = h('div');
    const editable = can('vlans.write');
    const draw = () => {
      const s = q.value.trim().toLowerCase();
      const rows = vlans.filter((v) => (!cls.value || v.class === cls.value)
        && (!hideRule.checked || !/-N\d{3}[A-Z]?$/.test(v.vlanKey))
        && (!s || [v.vlanKey, v.vlanName, v.vlanId, ...(v.aliases || [])].join(' ').toLowerCase().includes(s)));
      mount(box, h('p', { class: 'muted small' }, `${rows.length} of ${vlans.length}`), table([
        { label: 'Key', value: (v) => h('code', {}, v.vlanKey) },
        { label: 'ID', value: (v) => v.vlanId ?? '—', class: 'num' },
        { label: 'Name', value: (v) => v.vlanName },
        { label: 'Aliases', value: (v) => (v.aliases || []).join(', ') },
        { label: 'Class', value: (v) => v.class || '' },
        { label: 'Zone', value: (v) => v.securityZone || h('span', { class: 'muted' }, 'none') },
        { label: 'Status', value: (v) => chip(v.status) },
        { label: 'Description', value: (v) => v.description || '' },
        { label: '', value: (v) => rowActions(
          button('Where used', () => vlanUsage(v), 'small'),
          editable ? button('Edit', () => vlanDialog(v, refresh), 'small') : null,
          editable ? button('Delete', () => deleteVlan(v, refresh), 'small') : null) },
      ], rows.slice(0, 500)));
    };
    q.addEventListener('input', draw);
    [cls, hideRule].forEach((el) => el.addEventListener('change', draw));
    draw();
    return h('div', {},
      h('div', { class: 'row' }, q, cls, h('label', { class: 'check' }, hideRule, ' hide VLANs generated by bulk rules'), h('span', { class: 'spacer' }),
        editable ? button('Add VLAN', () => vlanDialog(null, refresh), 'primary') : null),
      box);
  },

  // ========================================================================= host pools
  async roles(refresh) {
    const [roles, vlans] = await Promise.all([get('/host-roles'), get('/vlans')]);
    const editable = can('hostroles.write');
    return h('div', {},
      datalist('dl-lib-vlans', vlans.map((v) => v.vlanKey)),
      h('div', { class: 'row' },
        h('p', { class: 'muted' }, 'A host pool is a set of standard positions used at every site: e.g. WDC01 is always .61 on the VLANs the pool lives on. Positions are index.octet (1.10 = second /24 of a supernet, octet 10). Pools sharing a VLAN can\'t collide, and a change can\'t break a released template.'),
        h('span', { class: 'spacer' }),
        editable ? button('Add host pool', () => roleDialog(null, refresh), 'primary') : null),
      table([
        { label: 'Pool', value: (r) => h('span', {}, h('strong', {}, r.roleCode), h('div', { class: 'muted small' }, r.name || '')) },
        { label: 'Lives on VLANs', value: (r) => h('span', { class: 'chips' }, r.vlanKeys.length ? r.vlanKeys.map((k) => chip(k, 'draft')) : h('span', { class: 'muted' }, 'none')) },
        { label: 'Members', value: (r) => h('div', { class: 'chips' }, r.members.map((m) => h('span', { class: `member member-${m.kind}` }, m.name, ' ',
          h('span', { class: 'muted' }, m.kind === 'fixed' ? `.${String(m.hostPosition).replace(/^0\./, '')}${m.secondaryHostOctet != null ? ` (or .${m.secondaryHostOctet})` : ''}` : `.${m.rangeStart}–.${m.rangeEnd} ${m.kind}`)))) },
        { label: 'Mode', value: (r) => r.offsetMode },
        { label: '', value: (r) => (editable ? rowActions(
          button('Edit', () => roleDialog(r, refresh), 'small'),
          button('Members', () => membersDialog(r, refresh), 'small'),
          button('Delete', () => deleteRole(r, refresh), 'small')) : '') },
      ], roles));
  },

  // ========================================================================= address pools
  async pools(refresh) {
    const [pools, vrfs] = await Promise.all([get('/pools'), get('/vrfs')]);
    const editable = can('pools.write');
    return h('div', {},
      h('div', { class: 'row' }, h('p', { class: 'muted' }, 'Where site blocks come from. A pool hands out blocks of one size from its prefixes, skipping exclusions and anything already allocated.'),
        h('span', { class: 'spacer' }), editable ? button('Add pool', () => poolDialog(null, pools, vrfs, refresh), 'primary') : null),
      table([
        { label: 'Pool', value: (p) => h('span', {}, h('strong', {}, p.poolKey), h('div', { class: 'muted small' }, p.description || '')) },
        { label: 'Parent', value: (p) => p.parentPool || '—' },
        { label: 'VRF', value: (p) => p.vrf },
        { label: 'Hands out', value: (p) => (p.allocationPrefixLength ? `/${p.allocationPrefixLength}` : '—') },
        { label: 'Prefixes', value: (p) => p.prefixes.map((x) => h('code', { class: 'pill' }, x)) },
        { label: 'Excluded', value: (p) => p.exclusions.map((x) => h('code', { class: 'pill' }, x)) },
        { label: 'Blocks', value: (p) => p.blocksAllocated, class: 'num' },
        { label: '', value: (p) => (editable ? rowActions(
          button('Edit', () => poolDialog(p, pools, vrfs, refresh), 'small'),
          button('Prefixes', () => prefixesDialog(p, refresh), 'small'),
          button('Delete', () => deletePool(p, refresh), 'small')) : '') },
      ], pools));
  },

  // ========================================================================= VRFs
  async vrfs(refresh) {
    const vrfs = await get('/vrfs');
    const editable = can('pools.write');
    return h('div', {},
      h('div', { class: 'row' }, h('p', { class: 'muted' }, 'Routing domains. Two prefixes may only overlap if they\'re in different VRFs, and new allocations stay enterprise-unique by default.'),
        h('span', { class: 'spacer' }), editable ? button('Add VRF', () => vrfDialog(null, refresh), 'primary') : null),
      table([
        { label: 'VRF', value: (v) => h('strong', {}, v.vrfKey) },
        { label: 'Description', value: (v) => v.description || '' },
        { label: '', value: (v) => rowActions(
          button('Where used', () => vrfUsage(v), 'small'),
          editable ? button('Edit', () => vrfDialog(v, refresh), 'small') : null,
          editable ? button('Delete', () => deleteVrf(v, refresh), 'small') : null) },
      ], vrfs));
  },
};

// --------------------------------------------------------------------------- VLAN dialogs

async function vlanDialog(v, refresh) {
  const isNew = !v;
  const k = input({ value: v?.vlanKey || '', class: 'mono', placeholder: 'e.g. DCS-CCTV', disabled: !isNew });
  const id = input({ type: 'number', min: 2, max: 4094, value: v?.vlanId ?? '' });
  const name = input({ class: 'mono', value: v?.vlanName || '', placeholder: 'e.g. v2040-CCTV' });
  const aliases = input({ class: 'mono', value: (v?.aliases || []).join(', '), placeholder: 'comma separated, optional' });
  const cls = input({ class: 'mono', value: v?.class || '', placeholder: 'CORP, DCS, CSMS…' });
  const zone = select(ZONES, v?.securityZone || '');
  const status = select(['active', 'deprecated'], v?.status || 'active');
  const desc = input({ class: 'wide', value: v?.description || '' });
  const out = h('div');
  const ok = await modal({
    title: isNew ? 'Add VLAN' : `Edit ${v.vlanKey}`,
    body: h('div', {},
      h('div', { class: 'form-grid' },
        field('Key', k, isNew ? 'UPPER-KEBAB, unique, can\'t change later' : 'The key never changes'),
        field('VLAN ID', id, isNew ? null : 'Frozen while a live site carries this VLAN'),
        field('Name', name, 'Unique'), field('Aliases', aliases, 'Other names lookups accept'),
        field('Class', cls), field('Security zone', zone), isNew ? null : field('Status', status, 'Deprecated VLANs can\'t be added to new template releases'), field('Description', desc)),
      out),
    actions: [{ label: 'Cancel', value: false }, {
      label: isNew ? 'Add' : 'Save', kind: 'primary', value: true,
      validate: saver(out, () => (isNew
        ? post('/vlans', { vlanKey: k.value.trim().toUpperCase(), vlanId: id.value ? Number(id.value) : null, vlanName: name.value.trim(),
          aliases: list(aliases.value), class: cls.value.trim() || null, securityZone: zone.value || null, description: desc.value || null })
        : patch(`/vlans/${encodeURIComponent(v.vlanKey)}`, {
          vlanId: id.value ? Number(id.value) : null, clearVlanId: !id.value, vlanName: name.value.trim(), aliases: list(aliases.value),
          class: cls.value.trim(), securityZone: zone.value, status: status.value, description: desc.value }))),
    }],
  });
  if (ok) { toast(isNew ? 'VLAN added' : 'VLAN saved', 'success'); refresh(); }
}

function usageBody(u) {
  const section = (title, items) => (items.length ? [h('h3', {}, title), h('div', { class: 'chips' }, items)] : []);
  return h('div', {},
    !u.inUse ? h('p', {}, 'Nothing uses it.') : null,
    ...section('Template versions', (u.templates || []).map((t) => chip(`${t.template} · ${t.state}`, t.state))),
    ...section('Live sites', (u.sites || []).map((s) => (typeof s === 'string' ? chip(s, 'draft') : chip(`${s.site_code} · ${s.status}`, s.status)))),
    ...section('Host pools', (u.hostPools || []).map((p) => chip(p, 'draft'))),
    ...section('Address pools', (u.pools || []).map((p) => chip(p, 'draft'))),
    u.blocks ? h('p', {}, `${u.blocks} block(s) and ${u.subnets} subnet(s) are in it.`) : null);
}

async function vlanUsage(v) {
  const u = await get(`/vlans/${encodeURIComponent(v.vlanKey)}/usage`);
  modal({ title: `Where ${v.vlanKey} is used`, body: usageBody(u) });
}

async function deleteVlan(v, refresh) {
  if (!(await confirmBox(`Delete ${v.vlanKey}`, `Delete VLAN ${v.vlanKey} (${v.vlanName}) from the library?`, 'Delete', 'danger'))) return;
  try {
    await del(`/vlans/${encodeURIComponent(v.vlanKey)}`);
    toast(`${v.vlanKey} deleted`, 'success');
    refresh();
  } catch (err) {
    if (err.code !== 'IPAM-VLAN-IN-USE') { modal({ title: 'Couldn\'t delete', body: errorPanel(err) }); return; }
    const choice = await modal({
      title: `${v.vlanKey} is in use`,
      body: h('div', {}, h('p', {}, 'It can\'t be deleted while these use it. You can deprecate it instead: it stays where it\'s used, but can\'t go into new template releases.'), usageBody(err.body.usage)),
      actions: [{ label: 'Close', value: false }, v.status === 'deprecated' ? null : { label: 'Deprecate instead', kind: 'primary', value: true }].filter(Boolean),
    });
    if (choice) {
      try { await patch(`/vlans/${encodeURIComponent(v.vlanKey)}`, { status: 'deprecated' }); toast(`${v.vlanKey} deprecated`, 'success'); refresh(); } catch (e2) { modal({ title: 'Couldn\'t deprecate', body: errorPanel(e2) }); }
    }
  }
}

// --------------------------------------------------------------------------- host pool dialogs

function vlanPicker(initial) {
  const chosen = [...initial];
  const box = h('div', { class: 'chips' });
  const entry = input({ list: 'dl-lib-vlans', class: 'mono', placeholder: 'type a VLAN key…' });
  const draw = () => mount(box, chosen.length ? chosen.map((k) => h('span', { class: 'chip chip-draft' }, k, ' ',
    h('button', { type: 'button', class: 'btn-link', 'aria-label': `Remove ${k}`, onClick: () => { chosen.splice(chosen.indexOf(k), 1); draw(); } }, '✕'))) : h('span', { class: 'muted small' }, 'No VLANs yet'));
  const add = () => {
    const k = entry.value.trim().toUpperCase();
    if (k && !chosen.includes(k)) chosen.push(k);
    entry.value = '';
    draw();
  };
  entry.addEventListener('keydown', (e) => { if (e.key === 'Enter') { e.preventDefault(); add(); } });
  entry.addEventListener('change', add);
  draw();
  return { el: h('div', {}, box, h('div', { class: 'inline' }, entry, button('Add', add, 'small'))), values: () => chosen };
}

async function roleDialog(r, refresh) {
  const isNew = !r;
  const code = input({ value: r?.roleCode || '', class: 'mono', disabled: !isNew, placeholder: 'e.g. JMP' });
  const name = input({ value: r?.name || '', class: 'wide' });
  const mode = select([{ value: 'literalOctet', label: 'literal octet on the VLAN (default)' }, { value: 'fromNetwork', label: 'offset from the subnet start' }], r?.offsetMode || 'literalOctet');
  const pattern = input({ value: r?.hostnamePattern || '', class: 'mono', placeholder: '{CC}{SITE}{DOMAIN}{ROLE}{NN}' });
  const vlans = vlanPicker(r?.vlanKeys || []);
  const out = h('div');
  const ok = await modal({
    title: isNew ? 'Add host pool' : `Edit ${r.roleCode}`,
    wide: true,
    body: h('div', {},
      h('div', { class: 'form-grid' }, field('Pool code', code, isNew ? 'e.g. a STD-INF-DEVICE-NAMING role code' : null), field('Name', name), field('Positioning', mode), field('Hostname pattern', pattern)),
      field('Lives on VLANs', vlans.el, 'The pool\'s members get an address on each of these VLANs wherever a template binds them'),
      isNew ? h('p', { class: 'muted small' }, 'Add members after creating the pool, with the Members button.') : null,
      out),
    actions: [{ label: 'Cancel', value: false }, {
      label: isNew ? 'Add' : 'Save', kind: 'primary', value: true,
      validate: saver(out, () => (isNew
        ? post('/host-roles', { roleCode: code.value.trim(), name: name.value.trim() || null, vlanKeys: vlans.values(), offsetMode: mode.value, hostnamePattern: pattern.value.trim() || null, members: [] })
        : patch(`/host-roles/${encodeURIComponent(r.roleCode)}`, { name: name.value.trim(), vlanKeys: vlans.values(), offsetMode: mode.value, hostnamePattern: pattern.value.trim() }))),
    }],
  });
  if (ok) { toast(isNew ? 'Host pool added' : 'Host pool saved', 'success'); refresh(); }
}

async function membersDialog(r, refresh) {
  const rows = r.members.map((m) => ({ ...m }));
  const tbody = h('tbody');
  const draw = () => mount(tbody, rows.map((m, i) => {
    const name = input({ value: m.name, class: 'mono narrow' });
    name.addEventListener('change', () => { m.name = name.value.trim().toUpperCase(); });
    const kind = select(['fixed', 'range', 'reserved'], m.kind, { class: 'small-select' });
    kind.addEventListener('change', () => { m.kind = kind.value; draw(); });
    const pos = input({ value: m.hostPosition ?? '', class: 'mono narrow', placeholder: '61 or 1.10', disabled: m.kind !== 'fixed' });
    pos.addEventListener('change', () => { m.hostPosition = pos.value.trim() || null; });
    const sec = input({ type: 'number', min: 0, max: 255, value: m.secondaryHostOctet ?? '', class: 'narrow', disabled: m.kind !== 'fixed' });
    sec.addEventListener('change', () => { m.secondaryHostOctet = sec.value === '' ? null : Number(sec.value); });
    const start = input({ type: 'number', min: 0, max: 255, value: m.rangeStart ?? '', class: 'narrow', disabled: m.kind === 'fixed' });
    start.addEventListener('change', () => { m.rangeStart = start.value === '' ? null : Number(start.value); });
    const end = input({ type: 'number', min: 0, max: 255, value: m.rangeEnd ?? '', class: 'narrow', disabled: m.kind === 'fixed' });
    end.addEventListener('change', () => { m.rangeEnd = end.value === '' ? null : Number(end.value); });
    return h('tr', {}, h('td', {}, name), h('td', {}, kind), h('td', {}, pos), h('td', {}, sec), h('td', {}, start), h('td', {}, end),
      h('td', {}, button('↑', () => { if (i) { [rows[i - 1], rows[i]] = [rows[i], rows[i - 1]]; draw(); } }, 'small', { disabled: i === 0, title: 'Move up (instance order)' }),
        button('✕', () => { rows.splice(i, 1); draw(); }, 'small', { title: 'Remove' })));
  }));
  draw();
  const out = h('div');
  const ok = await modal({
    title: `${r.roleCode} members`,
    wide: true,
    body: h('div', {},
      h('p', { class: 'muted small' }, 'Fixed: one named host at a position (index.octet). Range: handed out next-available. Reserved: held for later. The order is the instance number for role lookups. Addresses already held at sites don\'t move.'),
      h('div', { class: 'table-wrap' }, h('table', { class: 'grid' },
        h('thead', {}, h('tr', {}, ['Name', 'Kind', 'Position', 'Secondary octet', 'Range start', 'Range end', ''].map((x) => h('th', {}, x)))), tbody)),
      h('p', {}, button('+ Add member', () => { rows.push({ name: `${r.roleCode}${String(rows.length + 1).padStart(2, '0')}`, kind: 'fixed', hostPosition: '' }); draw(); }, 'small')),
      out),
    actions: [{ label: 'Cancel', value: false }, {
      label: 'Save members', kind: 'primary', value: true,
      validate: saver(out, () => put(`/host-roles/${encodeURIComponent(r.roleCode)}/members`, rows.map((m) => ({
        name: m.name, kind: m.kind,
        hostPosition: m.kind === 'fixed' ? (m.hostPosition || null) : null,
        secondaryHostOctet: m.kind === 'fixed' ? m.secondaryHostOctet ?? null : null,
        rangeStart: m.kind !== 'fixed' ? m.rangeStart ?? null : null,
        rangeEnd: m.kind !== 'fixed' ? m.rangeEnd ?? null : null,
      })))),
    }],
  });
  if (ok) { toast('Members saved', 'success'); refresh(); }
}

async function deleteRole(r, refresh) {
  if (!(await confirmBox(`Delete ${r.roleCode}`, `Delete host pool ${r.roleCode} and its ${r.members.length} member(s)? Templates stop placing these hosts.`, 'Delete', 'danger'))) return;
  try { await del(`/host-roles/${encodeURIComponent(r.roleCode)}`); toast(`${r.roleCode} deleted`, 'success'); refresh(); } catch (err) { modal({ title: 'Couldn\'t delete', body: errorPanel(err) }); }
}

// --------------------------------------------------------------------------- address pool dialogs

async function poolDialog(p, pools, vrfs, refresh) {
  const isNew = !p;
  const key = input({ value: p?.poolKey || '', class: 'mono', disabled: !isNew, placeholder: 'e.g. SITE-POOL-NZ' });
  const parent = select([{ value: '', label: 'none (root pool)' }, ...pools.filter((x) => x.poolKey !== p?.poolKey).map((x) => x.poolKey)], p?.parentPool || 'ENTERPRISE', { disabled: !isNew });
  const vrf = select(vrfs.map((v) => v.vrfKey), p?.vrf || 'NXT', { disabled: !isNew });
  const size = select([{ value: '', label: 'doesn\'t allocate' }, ...[8, 12, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24].map((n) => ({ value: n, label: `/${n}` }))], p?.allocationPrefixLength ?? 16);
  const strategy = select(['first-fit', 'sequential-from-last'], p?.strategy || 'first-fit');
  const uniq = select([{ value: 'enterprise', label: 'enterprise-unique (default)' }, { value: 'vrf', label: 'unique within the VRF only' }], p?.uniqueness || 'enterprise');
  const status = select(['active', 'disabled'], p?.status || 'active');
  const desc = input({ class: 'wide', value: p?.description || '' });
  const prefixes = input({ class: 'mono wide', placeholder: 'e.g. 10.0.0.0/8, 172.16.0.0/12' });
  const exclusions = input({ class: 'mono wide', placeholder: 'e.g. 10.0.0.0/16' });
  const publicOk = h('input', { type: 'checkbox' });
  const out = h('div');
  const ok = await modal({
    title: isNew ? 'Add address pool' : `Edit ${p.poolKey}`,
    wide: true,
    body: h('div', {},
      h('div', { class: 'form-grid' },
        field('Pool key', key), field('Parent pool', parent, isNew ? 'Prefixes must sit inside the parent' : null), field('VRF', vrf),
        field('Hands out blocks of', size, !isNew && p.blocksAllocated ? 'Fixed while blocks are allocated' : null), field('Strategy', strategy),
        field('Uniqueness', uniq), isNew ? null : field('Status', status), field('Description', desc)),
      isNew ? h('div', { class: 'form-grid' }, field('Prefixes', prefixes, 'Comma separated'), field('Exclusions', exclusions, 'Never handed out')) : null,
      isNew ? h('label', { class: 'check' }, publicOk, ' Allow prefixes outside RFC 1918 / RFC 6598 private space') : null,
      out),
    actions: [{ label: 'Cancel', value: false }, {
      label: isNew ? 'Add' : 'Save', kind: 'primary', value: true,
      validate: saver(out, () => (isNew
        ? post('/pools', { poolKey: key.value.trim(), parentPool: parent.value || null, vrf: vrf.value, allocationPrefixLength: size.value ? Number(size.value) : null,
          strategy: strategy.value, uniqueness: uniq.value, description: desc.value || null, prefixes: list(prefixes.value), exclusions: list(exclusions.value), confirmNonPrivate: publicOk.checked })
        : patch(`/pools/${encodeURIComponent(p.poolKey)}`, { description: desc.value, allocationPrefixLength: size.value ? Number(size.value) : null, strategy: strategy.value, uniqueness: uniq.value, status: status.value }))),
    }],
  });
  if (ok) { toast(isNew ? 'Pool added' : 'Pool saved', 'success'); refresh(); }
}

async function prefixesDialog(p, refresh) {
  let current = p;
  const box = h('div');
  const out = h('div');
  const run = async (fn) => {
    mount(out);
    try { current = await fn(); draw(); } catch (err) { mount(out, errorPanel(err)); }
  };
  const draw = () => {
    const prefix = input({ class: 'mono', placeholder: 'e.g. 172.16.0.0/12' });
    const publicOk = h('input', { type: 'checkbox' });
    const excl = input({ class: 'mono', placeholder: 'e.g. 10.72.0.0/16' });
    const pill = (c, onRemove) => h('span', { class: 'chip chip-draft' }, c, ' ', h('button', { type: 'button', class: 'btn-link', 'aria-label': `Remove ${c}`, onClick: onRemove }, '✕'));
    mount(box,
      h('h3', {}, 'Prefixes (in allocation order)'),
      h('div', { class: 'chips' }, current.prefixes.length ? current.prefixes.map((c) => pill(c, () => run(() => api('DELETE', `/pools/${encodeURIComponent(p.poolKey)}/prefixes`, { query: { cidr: c } })))) : h('span', { class: 'muted' }, 'none')),
      h('div', { class: 'row' }, prefix, h('label', { class: 'check small' }, publicOk, ' public space is intended'),
        button('Add prefix', () => run(() => post(`/pools/${encodeURIComponent(p.poolKey)}/prefixes`, { cidr: prefix.value.trim(), confirmNonPrivate: publicOk.checked })), 'small')),
      h('h3', {}, 'Exclusions (never handed out)'),
      h('div', { class: 'chips' }, current.exclusions.length ? current.exclusions.map((c) => pill(c, () => run(() => api('DELETE', `/pools/${encodeURIComponent(p.poolKey)}/exclusions`, { query: { cidr: c } })))) : h('span', { class: 'muted' }, 'none')),
      h('div', { class: 'row' }, excl, button('Add exclusion', () => run(() => post(`/pools/${encodeURIComponent(p.poolKey)}/exclusions`, { cidr: excl.value.trim() })), 'small')));
  };
  draw();
  await modal({
    title: `${p.poolKey} prefixes and exclusions`,
    wide: true,
    body: h('div', {}, h('p', { class: 'muted small' }, `${p.blocksAllocated} block(s) allocated. A prefix with allocations can't be removed, and an exclusion can't cover space already allocated.`), box, out),
    actions: [{ label: 'Done', kind: 'primary', value: true }],
  });
  refresh();
}

async function deletePool(p, refresh) {
  if (!(await confirmBox(`Delete ${p.poolKey}`, `Delete address pool ${p.poolKey}?`, 'Delete', 'danger'))) return;
  try { await del(`/pools/${encodeURIComponent(p.poolKey)}`); toast(`${p.poolKey} deleted`, 'success'); refresh(); } catch (err) {
    modal({ title: `${p.poolKey} can't be deleted`, body: err.body?.usage ? h('div', {}, h('p', {}, err.message), usageBody({ ...err.body.usage, inUse: true, pools: err.body.usage.childPools })) : errorPanel(err) });
  }
}

// --------------------------------------------------------------------------- VRF dialogs

async function vrfDialog(v, refresh) {
  const isNew = !v;
  const key = input({ value: v?.vrfKey || '', class: 'mono', disabled: !isNew, placeholder: 'e.g. CSMS' });
  const desc = input({ class: 'wide', value: v?.description || '' });
  const out = h('div');
  const ok = await modal({
    title: isNew ? 'Add VRF' : `Edit ${v.vrfKey}`,
    body: h('div', {}, h('div', { class: 'form-grid' }, field('VRF key', key), field('Description', desc)), out),
    actions: [{ label: 'Cancel', value: false }, {
      label: isNew ? 'Add' : 'Save', kind: 'primary', value: true,
      validate: saver(out, () => (isNew ? post('/vrfs', { vrfKey: key.value.trim(), description: desc.value || null }) : patch(`/vrfs/${encodeURIComponent(v.vrfKey)}`, { description: desc.value }))),
    }],
  });
  if (ok) { toast(isNew ? 'VRF added' : 'VRF saved', 'success'); refresh(); }
}

async function vrfUsage(v) {
  const u = await get(`/vrfs/${encodeURIComponent(v.vrfKey)}/usage`);
  modal({ title: `Where ${v.vrfKey} is used`, body: usageBody(u) });
}

async function deleteVrf(v, refresh) {
  if (!(await confirmBox(`Delete ${v.vrfKey}`, `Delete VRF ${v.vrfKey}?`, 'Delete', 'danger'))) return;
  try { await del(`/vrfs/${encodeURIComponent(v.vrfKey)}`); toast(`${v.vrfKey} deleted`, 'success'); refresh(); } catch (err) {
    modal({ title: `${v.vrfKey} can't be deleted`, body: err.body?.usage ? h('div', {}, h('p', {}, err.message), usageBody(err.body.usage)) : errorPanel(err) });
  }
}
